spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 100MB
      max-request-size: 200MB

  application:
    name: arquivo-service
  #    http://dhan.com.br:8888
  cloud:
    config:
      enabled: true
      name: portal-config-server

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
#      http://dhan.com.br:9000/eureka

server:
  port: 9098

