spring:
  application:
    name: importacao-arquivo-service
  #    http://dhan.com.br:8888
  cloud:
    config:
      enabled: true
      name: portal-config-server
server:
  port: 9898


portal:
  cassandra:
    key-space-name: ks_importacao_arquivo
    contact-points: 172.30.87.52